name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "test"
